### ISSUE TITLE
Use buildx instead of build for docker Images

### ISSUE THREAD

**Issue by 5olu7ion** [microsoft/azure-pipelines-tasks-common-packages#273]
We get a warning in our azdo pipeline (Docker@2):
```
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/
```

Are there plans, to support the "new" buildx command? 
Code: https://github.com/microsoft/azure-pipelines-tasks-common-packages/blob/470ed3de23c0485a248ec8b15df62628705f65e1/common-npm-packages/docker-common/dockercommandutils.ts#L20 

Reference: https://docs.docker.com/engine/deprecated/#deprecated-engine-features-1  (Legacy Builder for Linux Images)

**Comment by davidreher** [comment]
Here is some more info on the [deprecation itself](https://docs.docker.com/engine/deprecated/#legacy-builder-for-linux-images).

**Comment by msherms2** [comment]
Anything on this? Looks like buildx is used for attestations which may help docker scout results. Any plans for this?

**Comment by jmos5156** [comment]
Would be great to hear of any plans for this. Azure docker image caching is lacking a little but coupled with buildx caching it could work really well.

**Comment by msherms2** [comment]
I'm afraid I've noticed a really consistent pattern as of late where no one on MS responds to any of these. I don't know why but I think someone dropped the ball on this channel, either intentionally or not.

**Comment by Matthew0x** [comment]
You can use ACR tasks to build buildx with buildkit, then use buildx to build image with buildx features support.
Of course, using one CLI call/ADO task would make life simple, but it is what it is...

```yml
- task: AzureCLI@2
  name: acrBuildx
  displayName: "ACR task"
  inputs:
    azureSubscription: <service-connection-name>
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd "<acr-task-folder-path>"
      az acr run . --file <acr-task-name>.yml --registry $ACR_NAME \
      --set ACR_ARGUMENT_NAME=$ACR_ARGUMENT_NAME
  env:
    ACR_NAME: <value>
    ACR_ARGUMENT_NAME: <value>
```

```yml
version: v1.1.0
steps:
  - id: buildx
    cmd: >- # Multiline support
      docker build https://github.com/docker/buildx.git#v0.19 --platform=local --output=. &&
      mkdir -p ~/.docker/cli-plugins && cp -r buildx ~/.docker/cli-plugins/docker-buildx
    env: ["DOCKER_BUILDKIT=1"]
    when: ["-"]
  - id: builder
    cmd: >-
      buildx create --name friendly_squirrel --driver docker-container
    when: ["buildx"]
    env: ["DOCKER_BUILDKIT=1"]
  - id: image
    cmd: >-
      buildx build . --file <dockerfile-name>.dockerfile --builder=friendly_squirrel --load --tag <image-name:version>
      --build-arg ACR_ARGUMENT_NAME={{.Values.ACR_ARGUMENT_NAME}
    when: ["builder"]
    env: ["DOCKER_BUILDKIT=1"]
  - push: ["$Registry/<image-name:version>"]
    when: ["image"]
```

Here is some 'official documentation' from 6 years ago for reference:
https://github.com/Azure/acr/blob/main/docs/tasks/buildx/build_with_cache.yaml
https://github.com/Azure/acr/blob/main/docs/tasks/buildx/README.md

**Comment by Matthew0x** [comment]
You can use ACR tasks to build buildx with buildkit, then use buildx to build image with buildx features support.
Of course, using one CLI call/ADO task would make life simple, but it is what it is...

e.g.  `az acr run . --file <acr-task-name>.yml --registry $ACR_NAME`

You can nest it in e.g. AzureCLI@2 (or Bash)

```yml
- task: AzureCLI@2
  name: adoBuildx
  inputs:
...
    inlineScript: |
      az acr run . --file <acr-task-name>.yml --registry $ACR_NAME \
      --set BUILDX_ARGUMENT_NAME=$BUILDX_ARGUMENT_NAME
  env:
    ACR_NAME: <value>
    BUILDX_ARGUMENT_NAME: <value>
```

```yml
version: v1.1.0
steps:
  - id: buildx
    cmd: >- # Multiline support
      docker build https://github.com/docker/buildx.git#v<buildx-version> --platform=local --output=. &&
      mkdir -p ~/.docker/cli-plugins && mv buildx ~/.docker/cli-plugins/docker-buildx
    env: ["DOCKER_BUILDKIT=1"]
    when: ["-"]
  - id: builder
    cmd: >-
      buildx create --name friendly_squirrel --driver docker-container
    when: ["buildx"]
    env: ["DOCKER_BUILDKIT=1"]
  - id: image
    cmd: >-
      buildx build . --file <dockerfile-name>.dockerfile --builder=friendly_squirrel --load --tag <image-name:version>
      --build-arg BUILDX_ARGUMENT_NAME={{.Values.BUILDX_ARGUMENT_NAME}
    when: ["builder"]
    env: ["DOCKER_BUILDKIT=1"]
```

Here is some 'official documentation' from 6 years ago for reference:
https://github.com/Azure/acr/blob/main/docs/tasks/buildx/README.md
https://github.com/Azure/acr/blob/main/docs/tasks/buildx/bootstrap.yaml
https://github.com/Azure/acr/blob/main/docs/tasks/buildx/build_with_cache.yaml
